//
//  ListPhotosModels.swift
//  BeblueRovers
//
//  Created by Silvia Florido on 24/02/19.
//  Copyright (c) 2019 Silvia Florido. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListPhotos
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    enum FetchPhotos
    {
        struct Request
        {
        }
        struct Response
        {
            var photos: [Photo]
        }
        struct ViewModel
        {
            struct DisplayedPhoto
            {
                var id: String
                var camera: String
                var earthDate: Date
                var img_src: String
                
            }
            var displayedPhotos: [DisplayedPhoto]
        }
    }
}
