//
//  ListPhotosModels.swift
//  BeblueRovers
//
//  Created by Silvia Florido on 24/02/19.
//  Copyright (c) 2019 Silvia Florido. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListPhotos
{
    // MARK: Use cases
    enum FetchPhotos
    {
        struct Request
        {
            var rover: String
        }
        struct Response
        {
            var photos: [Photo]
        }
        struct ViewModel
        {
            struct DisplayedPhoto
            {
                var cameraName: String
                var cameraFullName: String
                var date: String
                var img_src: String
                var img_data: Data?
                
            }
            var displayedPhotos: [DisplayedPhoto]
        }
    }
    
    enum FetchImage
    {
        struct Request
        {
            var urlStr: String
        }
        struct Response
        {
            var image: UIImage
        }
        struct ViewModel
        {
            var image: UIImage
        }
    }
}
