//
//  ListPhotosPresenter.swift
//  BeblueRovers
//
//  Created by Silvia Florido on 24/02/19.
//  Copyright (c) 2019 Silvia Florido. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPhotosPresentationLogic
{
    func presentPhotos(response: ListPhotos.FetchPhotos.Response)
    func presentFetchError()
}

class ListPhotosPresenter: ListPhotosPresentationLogic
{
    weak var viewController: ListPhotosDisplayLogic?
    
    
    // MARK: Present Photos
    func presentPhotos(response: ListPhotos.FetchPhotos.Response)
    {
        var displayedPhotos: [ListPhotos.FetchPhotos.ViewModel.DisplayedPhoto] = []
//        for photo in response.photos {
//            let date = dateFormatter.string(from: order.date)
//            let total = currencyFormatter.string(from: order.total)
//            let displayedOrder = ListOrders.FetchOrders.ViewModel.DisplayedOrder(id: order.id!, date: date, email: order.email, name: "\(order.firstName) \(order.lastName)", total: total!)
//            displayedOrders.append(displayedOrder)
//        }
//        let viewModel = ListOrders.FetchOrders.ViewModel(displayedOrders: displayedOrders)
//        viewController?.displayFetchedOrders(viewModel: viewModel)
//        let viewModel = ListPhotos.FetchPhotos.ViewModel(displayedPhotos: response)
//        viewController?.displayPhotos(viewModel: viewModel)
    }
    
    func presentFetchError() {
        
    }
    
    let dateFormatter: DateFormatter = {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .short
        dateFormatter.timeStyle = .none
        return dateFormatter
    }()
}
