//
//  ListPhotosPresenter.swift
//  BeblueRovers
//
//  Created by Silvia Florido on 24/02/19.
//  Copyright (c) 2019 Silvia Florido. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPhotosPresentationLogic
{
    func presentPhotos(response: ListPhotos.FetchPhotos.Response)
}

class ListPhotosPresenter: ListPhotosPresentationLogic
{
    weak var viewController: ListPhotosDisplayLogic?
    
    
    // MARK: Present Photos
    func presentPhotos(response: ListPhotos.FetchPhotos.Response)
    {
//        let viewModel = ListPhotos.FetchPhotos.ViewModel(displayedPhotos: response)
//        viewController?.displayPhotos(viewModel: viewModel)
    }
}
