//
//  PhotosWorker.swift
//  BeblueRovers
//
//  Created by Silvia Florido on 24/02/19.
//  Copyright (c) 2019 Silvia Florido. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotosStoreProtocol
{
    func fetchPhotos(rover:String, date:String, completionHandler: @escaping ([Photo]?, PhotosStoreError?) -> Void)
    func fetchImage(_ urlString: String, completionHandlerForImage: @escaping (Data?, PhotosStoreError?) -> Void)
}

class PhotosWorker
{
    var photosStore: PhotosStoreProtocol
    
    init(photosStore: PhotosStoreProtocol) {
        self.photosStore = photosStore
    }

    
    func fetchPhotos(rover: String, completionHandler: @escaping ([Photo]?, PhotosStoreError?) -> Void)
    {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        let date = dateFormatter.date(from: "2015-6-3")!
        let dateStr = dateFormatter.string(from: date)
        
        photosStore.fetchPhotos(rover: rover, date: dateStr) { (photos, photosStoreError) in
            if let photos = photos {
                DispatchQueue.main.async {
                    completionHandler(photos, nil)
                }
            } else {
                DispatchQueue.main.async {
                    completionHandler(nil, photosStoreError)
                }
            }
        }
    }
    
    
    func fetchImage(_ urlString: String, completionHandlerForImage: @escaping (Data?, PhotosStoreError?) -> Void) {
        photosStore.fetchImage(urlString) { (data, photosStoreError) in
            if let data = data {
                
                DispatchQueue.main.async {
                    completionHandlerForImage(data, nil)
                }
            } else {
                DispatchQueue.main.async {
                    completionHandlerForImage(nil, photosStoreError)
                }
            }
        }
    }
    
    
    
    
}




// MARK: - store operation errors

enum PhotosStoreError: Equatable, Error
{
    case CannotFetch(String)
    case CannotCreate(String)
    case CannotUpdate(String)
    case CannotDelete(String)
}

func ==(lhs: PhotosStoreError, rhs: PhotosStoreError) -> Bool
{
    switch (lhs, rhs) {
    case (.CannotFetch(let a), .CannotFetch(let b)) where a == b: return true
    case (.CannotCreate(let a), .CannotCreate(let b)) where a == b: return true
    case (.CannotUpdate(let a), .CannotUpdate(let b)) where a == b: return true
    case (.CannotDelete(let a), .CannotDelete(let b)) where a == b: return true
    default: return false
    }
}
